site_name: Yunzinan的知识库
site_description: 存放和分享笔者的一些笔记和随笔
site_author: Yunzinan

repo_name: 'Note_Base'
repo_url: 'https://github.com/yunzinan/Note_Base'


theme:
  name: material
  language: 'zh'
  features:
  - navigation.tabs
  palette:
    primary: 'Blue'
    accent: 'Lime'
  feature:
    tabs: false
  font:
    text: 'Jetbrains Mono'
    code: 'Jetbrains Mono'
  language: 'zh'
  highlightjs: true

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.emoji:  # 表情
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav: # 导航
- 主页: index.md
- 数学:
      - 微积分II: 
        - chap 1: Math/Caculus/Calculus-II-notes-chapt1.md
        - chap 2: Math/Caculus/Calculus-II-notes-chapt2.md
        - chap 3: Math/Caculus/Calculus-II-notes-chapt3.md
        - chap 4: Math/Caculus/Calculus-II-notes-chapt4.md
        - chap 5: Math/Caculus/Calculus-II-notes-chapt5.md
        - chap 6: Math/Caculus/Calculus-II-notes-chapt6.md
        - midterm review: Math/Caculus/Calculus-II-midterm-review.md
        - final review: Math/Caculus/Calculus-II-final-review.md
      - 离散数学: 
        - 代数系统: Math/DiscreteMath/离散数学笔记-代数结构-代数系统.md
        - 群与环: Math/DiscreteMath/离散数学笔记-代数结构-群与环.md
        - 格与布尔代数: Math/DiscreteMath/离散数学笔记-代数系统-格与布尔代数.md
        - 支配与着色: Math/DiscreteMath/离散数学笔记-图论-支配与着色.md
        - 欧拉图与哈密顿图: Math/DiscreteMath/离散数学笔记-图论部分-欧拉图与哈密顿图.md
        - 树: Math/DiscreteMath/离散数学笔记-图论部分-树.md
        - 图的基本概念: Math/DiscreteMath/离散数学笔记-图论部分-图的基本概念.md
        - 课堂笔记: Math/DiscreteMath/离散数学课堂笔记.md
      - 线性代数: Math/LinearAlgebra/Linear-algebra-notes.md
- 计算机科学:
      - 力扣刷题笔记: ComputerScience/力扣刷题笔记.md
      - 高级程序设计: ComputerScience/高级程序设计读书笔记.md
      - 数据结构: ComputerScience/数据结构.md
      - 数字逻辑与计算机组成: ComputerScience/数电计组.md
- 化学: 
  - 大学化学: Chemistry/大学化学笔记.md
  - 有机化学: Chemistry/有机化学笔记.md
  - 仪器分析: Chemistry/仪器分析笔记.md
  - 仪器分析作业: Chemistry/仪器分析作业.md
- 技能树:
      - Jupyter Notebook: SkillMap/Jupyter-notebook快速入门.md
      - 爬虫入门: SkillMap/WebCrawlingNotes.md
- 课堂笔记: 
    - 马原: LectureNotes/马原复习提纲.md
    - 普通物理I: LectureNotes/普通物理I复习笔记.md
    - 中国近代史纲要: LectureNotes/中国近代史纲要笔记.md
    - 高级程序设计: LectureNotes/高级程序设计.md
- 随笔:
      - 可积一定有原函数吗?: InformalEssay/一个小问题-可积一定有原函数吗.md
      - 22SummerReview: InformalEssay/22SummerReview.md
      - 对个人笔记系统的思考: InformalEssay/对个人笔记系统的思考.md
      - 都是语法惹的祸[待完成]: InformalEssay/一些LaTeX语法的问题.md
- OJ:
  - 警钟长鸣: CheatSheet/OJ/警钟长鸣-题单.md
  - 每日一题题单: CheatSheet/OJ/everydayAC.md
- CheatSheet:
  - mkdocs扩展语法: CheatSheet/mkdocs扩展语法.md